dependencyTypes:
  - "dev"
  - "overrides"
  - "peer"
  - "pnpmOverrides"
  - "prod"
  - "resolutions"

sortFirst:
  - "name"
  - "version"
  - "description"
  - "homepage"
  - "packageManager"
  - "license"
  - "private"
  - "author"
  - "keywords"
  - "sideEffects"
  - "main"
  - "module"
  - "types"
  - "exports"
  - "repository"
  - "engines"
  - "workspaces"
  - "scripts"
  - "peerDependencies"
  - "dependencies"
  - "devDependencies"

sortAz:
  - "contributors"
  - "dependencies"
  - "devDependencies"
  - "keywords"
  - "peerDependencies"
  - "resolutions"
